name: Deploy to GitHub Pages
on:
  push:
    branches: [ test ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish .NET Core Project
        run: dotnet publish KindleNotes/KindleNotes/KindleNotes.csproj -c Release -o release --nologo
      # changes the base-tag in index.html from '/' to 'KindleNotesParser' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to KindleNotesParser
        run: sed -i 's/<base href="\/" \/>/<base href="\/KindleNotesParser\/" \/>/g' release/wwwroot/index.html
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot 
